In [9]:
#class정의, class생성
#class 클래스명:
#클래스명() >> 생성자 >> instance (객체)

class Aclass:
    def __init__(self,num1, num2):   # 생성자 실행시 자동으로 실행
        self.num1 = num1
        self.num2 = num2
        print("class 생성")
        
    def __del__(self): #프로그램 종료시 자동으로 실행
        print("class 소멸")
        
    def get_sum(self):
        print("class 내부 함수 실행")
        return (self.num1 + self.num2)
    
a = Aclass(10,20) # 생성자 >> class 내부의 __init__ 함수가 실행
print(a.num1, a.num2, a.get_sum())
b = Aclass(30,40)
print(b.num1, b.num2, b.get_sum())

a_list = [a,b]
a_list[0],get_sum()

class 생성
class 소멸
class 내부 함수 실행
10 20 30
class 생성
class 소멸
class 내부 함수 실행
30 40 70


NameError: name 'get_sum' is not defined

In [20]:
class Student:
    def __init__(self, name, kor, eng):
        self.name = name
        self.kor = kor
        self.eng = eng
    
    def file_write(self):
        fp.write(self.name + ','+ str(self.kor) +',' + str(self.eng)+'\n')

In [39]:
fp = open("class_file.txt","a+")
try:
    while input_data() != 'q':  # 'q' 리턴되면 종료
        continue
    data = search_data()     
    if data:
        print("{} : {}, {}".format(data[0],data[1],data[2]))
    else:
        print("검색할 자료 없음")
              
except Exception as e:
    print("error", e)
finally:
    fp.close()

error name 'input_data' is not defined


In [40]:
fp = open("class_file.txt","r+")
for line in  fp:
    print(line)
fp.close()

,40,50

철수,60,70

영수,70,70

영희 70 70,50,60



In [41]:
def input_data():
    name = input("이름 : ")
    if name == 'q':
        return 'q'
    while True:
        score = input("국어, 영어 점수 입력 : ( 50 40)").split() 
        if len(score) == 2:
            break

    student = Student(name, int(score[0]), int(score[1]))
    student.file_write()
    return
    
def search_data():
    fp.seek(0)
    s_name = input("검색할 이름 입력 ")
    for line in fp:
        line_data = line.split(',')
        if s_name == line_data[0]:
            return line_data
    return 

In [42]:
def input_data():
    name = input("이름 :")
    if name == 'q';
    
    return 'q'

SyntaxError: invalid syntax (<ipython-input-42-2ac797beec2b>, line 3)

In [43]:
class student: # 학생 인스턴스에 대한 속성과 메서드를 정의
    # 초기화 class 생성시 생성
    def __init__(self.name,korean,math,english,science ):
        self.name = name
        self.korean = korean
        self.math = math
        self.math = math
        self.english = english
        self.science = 
    #총점 구함
    def get_sum(self):
        return self.korean + self.english + self.math + self.science
    #평균 구함
    def get_avg(self):
        return self.get_sum()/4
    #프린트
    def to_string(self):
        return "{}\t{}\t{}\t{}\t{}\t{}\t{}".format(self.name,
                                                self.get_sum(),
                                                self.get_avg(),
                                                self.korean,self.english
                                                self.math.self.science

SyntaxError: invalid syntax (<ipython-input-43-97842e975ac2>, line 3)

In [44]:
fp = open("class_file.txt"."a+")
try:
    while True: #무한반복
        name = input("이름: ")
        if name =='q':
            break
        score = int(input("점수 입력: "))
        student = student(name, score)
        student.file_write()
        
    data = search_dat()
    if data:
        print("{} : {}, {}".format(data[0],data[1],data[2]))
        

SyntaxError: invalid syntax (<ipython-input-44-f7cdc25e3063>, line 1)

In [45]:
# 학생 클래스를 선언합니다.
class Student:
    def study(self):
        print("공부를 합니다.")

# 선생님 클래스를 선언합니다.
class Teacher:
    def teach(self):
        print("학생을 가르칩니다.")

# 교실 내부의 객체 리스트를 생성합니다.
classroom = [Student(), Student(), Teacher(), Student(), Student()]

# 반복을 적용해서 적절한 함수를 호출하게 합니다.
for person in classroom:
    if isinstance(person, Student):
        person.study()
    elif isinstance(person, Teacher):
        person.teach()
 

공부를 합니다.
공부를 합니다.
학생을 가르칩니다.
공부를 합니다.
공부를 합니다.


In [46]:
# 학생 클래스를 선언합니다.
class Student:
    def study(self):
        print("공부를 합니다.")

# 선생님 클래스를 선언합니다.
class Teacher:
    def teach(self):
        print("학생을 가르칩니다.")

# 교실 내부의 객체 리스트를 생성합니다.
classroom = [Student(), Student(), Teacher(), Student(), Student()]

# 반복을 적용해서 적절한 함수를 호출하게 합니다.
for person in classroom:
    if isinstance(person, Student):
        person.study()
    elif isinstance(person, Teacher):
        person.teach()
 
YGL — 오늘 오전 11:57
# 모듈을 가져옵니다.
import math

# 클래스를 선언합니다.
class Circle:
    def __init__(self, radius):
        self.radius = radius
    def get_circumference(self):
        return 2 * math.pi * self.radius
    def get_area(self):
        return math.pi * (self.radius ** 2)

# 원의 둘레와 넓이를 구합니다.
circle = Circle(10)
print("원의 둘레:", circle.get_circumference())
print("원의 넓이:", circle.get_area())

SyntaxError: invalid character in identifier (<ipython-input-46-376a0a2f682a>, line 21)

In [47]:
class Parent:
    def __init__(self):
        self.value = "테스트"
        print("Parent 클래스의 __init()__ 메서드가 호출되었습니다.")
    def test(self):
        print("Parent 클래스의 test() 메서드입니다.")

# 자식 클래스를 선언합니다.
class Child(Parent):
    def __init__(self):
        Parent.__init__(self) 
        print("Child 클래스의 __init()__ 메서드가 호출되었습니다.")

# 자식 클래스의 인스턴스를 생성하고 부모의 메서드를 호출합니다.
child = Child()
child.test()
print(child.value)

Parent 클래스의 __init()__ 메서드가 호출되었습니다.
Child 클래스의 __init()__ 메서드가 호출되었습니다.
Parent 클래스의 test() 메서드입니다.
테스트


In [48]:
#numpy : 배열의 연산등을 쉽게 처리 가능하도록 하는 패키지
import numpy as np
a= np.arange(15).reshape(3,5)
print(a, type(a))
print(a.ndim, a.shape, a.size, a.dtype.name, a.dtype.itemsize)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] <class 'numpy.ndarray'>
2 (3, 5) 15 int32 4


In [49]:
np.arange(-10, 5, 0.5).reshape(5,6)

array([[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5],
       [ -7. ,  -6.5,  -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5],
       [ -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5,   4. ,   4.5]])

In [50]:
# ndarray creation
# create an array from a regular python list 

a1 = np.array([1.0, 2.0, 3.0])
a2 = np.array([[1.0, 2.0],[ 3.0, 4.0]])
print(a1, type(a1))
print(a2, type(a2))
print(a1.ndim, a1.shape, a1.size, a1.dtype)
print(a2.ndim, a2.shape, a2.size, a2.dtype)


[1. 2. 3.] <class 'numpy.ndarray'>
[[1. 2.]
 [3. 4.]] <class 'numpy.ndarray'>
1 (3,) 3 float64
2 (2, 2) 4 float64


In [51]:
#list에서 array를 생성하는 방법
a_list = [1,2,3,4,5,6]

print(type(a_list),type(a_array, a_list, a_array)
      a_array.shape

SyntaxError: invalid syntax (<ipython-input-51-c1af4384fef3>, line 5)

In [52]:
#Inf, Nan, 초기값 설정한 배열 생성
a = np.zeros(5)
b = np.ones((2,3,4), dtype='U4')
print(a, a.dtype.itemsize.b, b.dtype.itemsize )

AttributeError: 'int' object has no attribute 'b'

In [53]:
a = np.empty((4,3)) #초기화 하지 않아 쓰레기 값이 들어가 있음
a

array([[1.00455005e-311, 2.47032823e-322, 0.00000000e+000],
       [0.00000000e+000, 1.33511018e-306, 2.42336543e-057],
       [5.33384510e-091, 2.70237041e-056, 2.34084701e-057],
       [6.86564600e+169, 3.99910963e+252, 1.86248692e+160]])

In [54]:
x1 = np.array([1.0, 2.0, 3.0])
y1 = np.array([5.0, 10.0, 15.0])
x2 = np.array([[1.0, 2.0],[ 3.0, 4.0]]) 
y2 = np.array([[5.0,10.0],[15.0,20.0]]) 
z1 = np.array([-1.0, -2.0])
z2 = np.array([[5.0],[10.0],[15.0]])

# ndarray basic operation  
print(x1 + y1) 
print(x1 - y1) 
print(x1 * y1) 
print(x1 / y1) 
print(x2 + y2) 
print(x2 * y2)


[ 6. 12. 18.]
[ -4.  -8. -12.]
[ 5. 20. 45.]
[0.2 0.2 0.2]
[[ 6. 12.]
 [18. 24.]]
[[ 5. 20.]
 [45. 80.]]


In [55]:
#array 연산
x1= np.array([1,2,3])
y1= np.array([4,5,6])
x2 = np.array([[1,2],[3,4]])
z1 = np.array([-1,-2])
z2 = np.array([[1,2,3,4],[4,5,6,7,8]])

print(x1+y1)
print(x2 + z1) #broad cast : 반복 사용
print(x2.flatten()) #평탄화 1차원으로 변경
print(x1.reshape(2,2)) #1차원을 2차원으로
print(z2.reshape(2,2,2)) #reshap은 배열을 다시 재배치

[5 7 9]
[[0 0]
 [2 2]]
[1 2 3 4]


<ipython-input-55-706782d766c5>:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  z2 = np.array([[1,2,3,4],[4,5,6,7,8]])


ValueError: cannot reshape array of size 3 into shape (2,2)

In [56]:
#indexing, slicing, iterating
a = np.arange(10) ** 2
print(a)
print(a[2])
print(a[3:5])
print(-a[0 : 6: 2])
print(a[ : : -1])

b =a.reshape(2,5)
print(b)
print(b[ : , 1])
print(b[-1, -1])

[ 0  1  4  9 16 25 36 49 64 81]
4
[ 9 16]
[  0  -4 -16]
[81 64 49 36 25 16  9  4  1  0]
[[ 0  1  4  9 16]
 [25 36 49 64 81]]
[ 1 36]
81


In [57]:
a = np.array([[2,3,4],[5,6,2],[9,6,7]])
print(np.argmax(a, axis=1))

[2 1 0]


In [58]:
print(np.mean(a), np.var(a), np.median(a), len(a), a.size)

4.888888888888889 4.987654320987654 5.0 3 9


In [59]:
np.random.seed(100)
a = np.random.rand(5)
print(a)

[0.54340494 0.27836939 0.42451759 0.84477613 0.00471886]


In [60]:
np.random.choice(100,5, replace=False)

array([25, 51, 21, 26, 68])

In [61]:
#np.random.seed(100)
np.random.randint(10, size=(2,5))

array([[3, 7, 9, 0, 0],
       [5, 9, 6, 6, 5]])

In [62]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(x[ (x%3 ==0) & ( x%4 ==1)])
print((x%3==0) & ( x%4 ==1))

[9]
[False False False False False False False False  True False False False
 False False False False False False False False]


In [63]:
x[ x%4 ==1 ]

array([ 1,  5,  9, 13, 17])

In [64]:
[ x%3 ==0] and [x%4==1]

[array([ True, False, False, False,  True, False, False, False,  True,
        False, False, False,  True, False, False, False,  True, False,
        False, False])]

In [69]:
#1부터 100가지의 수중에서 3의 배수만 배열로 생성
arr = np.arange(1,101)
arr = arr[ arr% 3 ==0]
print("arr : ", arr)
#위에서 생성된 배열의 값 중에서 임의로 5개의 값을 출력
print("임의의 수 5개 출력 : ", np.random.choice(arr, 5, replace=False))
#위의 배열의 사이즈를 확인한 후 행이 3인 2차원 배열을 생성
arr_1 = arr.reshape(3, int(arr.size / 3 ))
#배열의 원소 중에서 5의 배수만 출력
print("5의 배수만 출력 : ", arr_1[ arr_1 % 5 ==0 ])

arr :  [ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
임의의 수 5개 출력 :  [ 3 24 48  6 21]
5의 배수만 출력 :  [15 30 45 60 75 90]
